name: PR opened

on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
          node-version: '16.x'
      
    - name: Install dependencies
      run: npm ci

    - name: Build app
      run: npm run build
